server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index login.html;
        try_files $uri $uri/ /login.html;
    }

    location /static/ {
        root /usr/share/nginx/html;
    }

    location /auth/ {
        proxy_pass http://backend-autenticacion:5000;
    }

    location /inv/ {
        proxy_pass http://backend-inventario:5001;
    }
}
